-- local config = {
--     cmd = {'/home/paras/Java/library/jdt-language-server-1.32.0-202402011424/bin/jdtls'},
--     root_dir = vim.fs.dirname(vim.fs.find({'gradlew', '.git', 'mvnw'}, { upward = true })[1]),
-- }
-- require('jdtls').start_or_attach(config)
-- 
-- local nmap = function(keys, func, desc)
--     if desc then
--         desc = 'LSP: ' .. desc
--     end
-- 
--     vim.api.nvim_set_keymap('n', keys, func, { silent = true, noremap = true})
-- end
-- 
-- local telescope_builtin = require('telescope.builtin')
-- 
-- nmap('<leader>rn', "<cmd>lua vim.lsp.buf.rename", '[R]e[n]ame')
-- nmap('<leader>ca', "<cmd>lua vim.lsp.buf.code_action", '[C]ode [A]ction')
-- 
-- nmap('gd', "<cmd>lua vim.lsp.buf.definition", 'Goto [D]efinition')
-- nmap('gr', "<cmd>lua telescope_builtin.lsp_references", '[G]oto [R]eferences')
-- nmap('gi', "<cmd>lua vim.lsp.buf.implementation", '[G]oto [I]mplementation')
-- nmap('<leader>D', "<cmd>lua vim.lsp.buf.type_definition", 'Type [D]efinition')
-- nmap('<leader>ds', "<cmd>lua telescope_builtin.lsp_document_symbols", '[D]ocument [S]ymbols')
-- nmap('<leader>ws', telescope_builtin.lsp_dynamic_workspace_symbols, '[W]orkspace [S]ymbols')
-- 
-- -- See `:help K` for why this keymap
-- nmap('K', vim.lsp.buf.hover, 'Hover Documentation')
-- nmap('<C-s>', vim.lsp.buf.signature_help, 'Signature Documentation')
-- 
-- -- Lesser used LSP functionality
-- nmap('gD', vim.lsp.buf.declaration, '[G]oto [D]eclaration')
-- nmap('<jeader>wa', vim.lsp.buf.add_workspace_folder, '[W]orkspace [A]dd Folder')
-- nmap('<leader>wr', vim.lsp.buf.remove_workspace_folder, '[W]orkspace [R]emove Folder')
-- nmap('<leader>wl', function()
--     print(vim.inspect(vim.lsp.buf.list_workspace_folders()))
-- end, '[W]orkspace [L]ist Folders')
